altTranslationKeyFormat: null
altTranslationMethod: site
fieldLayouts:
  1272fc47-fee0-4a8b-80d0-5c19ed9e14c6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-19T09:40:13+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: c61578a5-1e99-4edf-acec-42d50fc042c6
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            dateAdded: '2025-02-19T09:40:13+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: c70f2487-93f4-4e28-93b4-b204527c3030
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-12T16:17:51+00:00'
            elementCondition: null
            fieldUid: c670b800-a19f-4ca2-a056-283204e59d5d # Credit / License
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: addce637-1162-4b04-9b41-f84a4e16ffab
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b716d9f1-1e92-42c0-bf65-7e868c92a471
        userCondition: null
fs: uploadsFs
handle: uploads
name: Uploads
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: uploadsFs
transformSubpath: transforms
