columnSuffix: xlohqkic
handle: caption
instructions: null
name: 'Main Image - Image - Caption'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: c4438391-90e5-49b1-93bd-6fcbbd3aed62 # Simple
  createButtonLabel: null
  defaultTransform: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: site
type: craft\ckeditor\Field
