columnSuffix: null
handle: projectLinks
instructions: null
name: 'Project Links'
searchable: false
settings:
  addRowLabel: 'Add a row'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Name
            -
              - handle
              - name
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - 'Link URL'
            -
              - handle
              - linkURL
            -
              - width
              - ''
            -
              - type
              - url
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
        -
          - col2
          - ''
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: site
type: craft\fields\Table
