columnSuffix: goyaurwq
handle: text
instructions: null
name: Text
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 6fa1e10a-d063-4c10-a955-f1b3eda7e7ef # Standard
  createButtonLabel: null
  defaultTransform: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: true
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: site
type: craft\ckeditor\Field
