defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: af427185-4826-4e80-bd57-096797b92f4b # Project
handle: projects
maxAuthors: 1
name: Projects
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  af0bbe1c-3613-4775-8a01-965b68d4e56e: # English
    enabledByDefault: true
    hasUrls: true
    template: projects/_entry
    uriFormat: 'projects/{slug}'
  ddc3aedf-983b-4fa7-81eb-69fd761d71af: # German
    enabledByDefault: true
    hasUrls: true
    template: projects/_entry
    uriFormat: 'projects/{slug}'
type: channel
